package com.slobodastudio.smspanic.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emailMessageRecordDaoConfig;

    private final EmailMessageRecordDao emailMessageRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emailMessageRecordDaoConfig = daoConfigMap.get(EmailMessageRecordDao.class).clone();
        emailMessageRecordDaoConfig.initIdentityScope(type);

        emailMessageRecordDao = new EmailMessageRecordDao(emailMessageRecordDaoConfig, this);

        registerDao(EmailMessageRecord.class, emailMessageRecordDao);
    }
    
    public void clear() {
        emailMessageRecordDaoConfig.getIdentityScope().clear();
    }

    public EmailMessageRecordDao getEmailMessageRecordDao() {
        return emailMessageRecordDao;
    }

}
