package com.slobodastudio.smspanic.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EMAIL_MESSAGE_RECORD.
 */
public class EmailMessageRecord {

    private Long id;
    private String adresses;
    private String subject;
    private String body;
    private String attachment;
    private java.util.Date time;

    public EmailMessageRecord() {
    }

    public EmailMessageRecord(Long id) {
        this.id = id;
    }

    public EmailMessageRecord(Long id, String adresses, String subject, String body, String attachment, java.util.Date time) {
        this.id = id;
        this.adresses = adresses;
        this.subject = subject;
        this.body = body;
        this.attachment = attachment;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAdresses() {
        return adresses;
    }

    public void setAdresses(String adresses) {
        this.adresses = adresses;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

}
